-- ============================================================================
-- CODEX NOVA DATABASE IMPORT
-- Generated: 2025-08-19T11:58:43.382Z
-- Brands: 12
-- Products: 87
-- Rate Plans: 266
-- ============================================================================

-- STEP 1: BACKUP EXISTING DATA
CREATE TABLE IF NOT EXISTS brands_backup_1755604723383 AS SELECT * FROM brands;
CREATE TABLE IF NOT EXISTS products_backup_1755604723383 AS SELECT * FROM products;
CREATE TABLE IF NOT EXISTS rate_plans_backup_1755604723383 AS SELECT * FROM rate_plans;

-- STEP 2: CLEAR EXISTING DATA
DELETE FROM rate_plans;
DELETE FROM products;
DELETE FROM brands;

-- STEP 3: INSERT BRANDS
INSERT INTO brands (code, name, country) VALUES ('AP', 'Aftenposten', 'NO');
INSERT INTO brands (code, name, country) VALUES ('AB', 'Aftonbladet', 'SE');
INSERT INTO brands (code, name, country) VALUES ('BT', 'Bergens Tidende', 'NO');
INSERT INTO brands (code, name, country) VALUES ('E24', 'E24', 'NO');
INSERT INTO brands (code, name, country) VALUES ('OMNI', 'Omni', 'SE');
INSERT INTO brands (code, name, country) VALUES ('PM-NO', 'Podme NO', 'NO');
INSERT INTO brands (code, name, country) VALUES ('R24', 'Randaberg24', 'NO');
INSERT INTO brands (code, name, country) VALUES ('SA', 'Stavanger Aftenblad', 'NO');
INSERT INTO brands (code, name, country) VALUES ('SVD', 'Svenska Dagbladet', 'SE');
INSERT INTO brands (code, name, country) VALUES ('VEK', 'VektKlubb', 'NO');
INSERT INTO brands (code, name, country) VALUES ('VG', 'Verdens Gang', 'NO');
INSERT INTO brands (code, name, country) VALUES ('W', 'Wellobe', 'NO');

-- STEP 4: INSERT PRODUCTS
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'A-magasinet', 'digital', 'AMAG');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Aftenposten mandag til lørdag', 'print', 'D16');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Aftenposten torsdag til lørdag', 'print', 'D46');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Basis', 'digital', 'BAS');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Duo', 'digital', 'DUO');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Full Tilgang', 'digital', 'FT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Full Tilgang Helg', 'print', 'WFT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Full Ttlgang Uke', 'print', 'KFT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Helg', 'print', 'W');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Magasin+', 'digital', 'MP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Solo', 'digital', 'SOLO');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Uke', 'digital', 'K');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Vink', 'digital', 'VINK');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AP'), 'Vinklubben', 'digital', 'VIN');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AB'), 'Aftonbladet e-tidning', 'digital', 'etid');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AB'), 'Aftonbladet Plus', 'digital', 'AB');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AB'), 'Aftonbladet Plus & Podme', 'digital', 'PM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AB'), 'Aftonbladet Superpaketet', 'digital', 'SP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'AB'), 'Plus & SvenskHockey.tv', 'digital', 'SH');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Basis', 'digital', 'BAS');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'BT mandag til fredag', 'print', 'D15');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Familie', 'digital', 'FAM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Full Tilgang', 'digital', 'FT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Full Tilgang Helg', 'print', 'WFT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Full Tilgang Komplett', 'print', 'KFT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Helg', 'digital', 'W');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Komplett', 'print', 'K');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'BT'), 'Premium', 'digital', 'P');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'E24'), 'Basis', 'digital', 'BAS');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'E24'), 'E24 og Dine Penger+', 'digital', 'DP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'E24'), 'E24 sanntidskurser', 'digital', 'SK');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'E24'), 'E24 uten deling', 'digital', 'X');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'E24'), 'Full Tilgang', 'digital', 'FT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'E24'), 'Pro', 'digital', 'PRO');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni annonsfritt', 'digital', 'D');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Bundle', 'digital', 'B');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Bundle Bas', 'digital', 'BB');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Ekonomi', 'digital', 'EK');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Ekonomi Bas', 'digital', 'EKB');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Mer', 'digital', 'MER');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Mer Bas', 'digital', 'MERB');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'OMNI'), 'Omni Superpaketet', 'digital', 'SP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'PM-NO'), 'Podme NO', 'digital', 'PM-NO');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'R24'), 'Randaberg24', 'digital', 'R24');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Aftenbladet mandag til fredag', 'print', 'D15');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Basis', 'digital', 'BAS');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Familie', 'digital', 'FAM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Full Tilgang', 'digital', 'FT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Full Tilgang Helg', 'print', 'WFT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Full Tilgang Komplett', 'print', 'KFT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Helg', 'print', 'W');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Komplett', 'print', 'K');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SA'), 'Premium', 'digital', 'P');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD digital premium', 'digital', 'DM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD digital premium SP', 'digital', 'DP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD digital standard', 'digital', 'DS');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD digital standard & Podme', 'digital', 'DSPM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD komplett alla dagar', 'print', 'KA');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD komplett helg', 'print', 'KH');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD komplett sexdagars', 'print', 'K6');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD komplett tredagars', 'print', 'K3');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD komplett vardag', 'print', 'KV');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD söndag', 'print', 'SON');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD Superpaketet', 'digital', 'SP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD Superpaketet - tillägg alla dagar', 'print', 'AO-KA');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD Superpaketet - tillägg digital premium', 'digital', 'AO-DM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD Superpaketet - tillägg helg', 'print', 'AO-KH');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD taltidning', 'digital', 'TAL');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD taltidning - tillägg', 'digital', 'AO-TAL');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'SVD'), 'SvD Vinklubb', 'digital', 'V');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VEK'), 'Vektklubb', 'health', 'VEK');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'Dine Penger+', 'digital', 'DP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'MinMote strikk', 'digital', 'MM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG eavis', 'digital', 'eavis');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG eavis med VG+', 'digital', 'VG');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG Weekend fredag-lørdag', 'print', 'W56');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG Weekend hele helgen', 'print', 'W');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG Weekend lørdag-søndag', 'print', 'W67');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+', 'digital', 'VG');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ Basis', 'digital', 'BAS');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ Flex', 'print', 'FT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ Full Tilgang', 'digital', 'FT');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ og Dine Penger+', 'digital', 'DP');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ og PodMe', 'digital', 'PM');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ Sport', 'digital', 'S');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'VG'), 'VG+ Total', 'digital', 'T');
INSERT INTO products (brand_id, name, type, shortcode) VALUES ((SELECT id FROM brands WHERE code = 'W'), 'Wellobe', 'health', 'W');

-- STEP 5: INSERT RATE PLANS
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'A-magasinet'), 'W', 'Week', 107, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'A-magasinet'), 'M', 'Month', 499, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'A-magasinet'), 'Q', 'Quarter', 1497, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'A-magasinet'), 'H', '6 months', 2994, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'A-magasinet'), 'Y', 'Year', 5988, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Basis'), 'M', 'Month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Duo'), 'W', 'Week', 67, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Duo'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Duo'), 'Q', 'Quarter', 897, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Duo'), 'H', '6 months', 1794, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Duo'), 'Y', 'Year', 3588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang'), 'W', 'Week', 87, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang'), 'M', 'Month', 379, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang'), 'Q', 'Quarter', 1137, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang'), 'H', '6 months', 2274, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang'), 'Y', 'Year', 4548, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang Helg'), 'M', 'Month', 638, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang Helg'), 'Q', 'Quarter', 1914, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang Helg'), 'H', '6 months', 3828, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Tilgang Helg'), 'Y', 'Year', 7656, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Ttlgang Uke'), 'M', 'Month', 838, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Ttlgang Uke'), 'Q', 'Quarter', 2514, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Ttlgang Uke'), 'H', '6 months', 5028, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Full Ttlgang Uke'), 'Y', 'Year', 10056, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Helg'), 'W', 'Week', 123, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Helg'), 'M', 'Month', 569, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Helg'), 'Q', 'Quarter', 1707, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Helg'), 'H', '6 months', 3414, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Helg'), 'Y', 'Year', 6828, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Magasin+'), 'W', 'Week', 34, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Magasin+'), 'M', 'Month', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Magasin+'), 'Q', 'Quarter', 599, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Magasin+'), 'H', '6 months', 1099, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Magasin+'), 'Y', 'Year', 1999, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Solo'), 'M', 'Month', 249, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Solo'), 'Q', 'Quarter', 747, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Solo'), 'H', '6 months', 1494, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Solo'), 'Y', 'Year', 2988, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Uke'), 'W', 'Week', 165, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Uke'), 'M', 'Month', 769, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Uke'), 'Q', 'Quarter', 2307, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Uke'), 'H', '6 months', 4614, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Uke'), 'Y', 'Year', 9228, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Vink'), 'M', 'Month', 39, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Vinklubben'), 'W', 'Week', 6, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AP' AND p.name = 'Vinklubben'), 'Y', 'Year', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AB' AND p.name = 'Aftonbladet e-tidning'), 'M', 'Month', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AB' AND p.name = 'Aftonbladet Plus'), 'M', 'Month', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AB' AND p.name = 'Aftonbladet Plus'), 'Y', 'Year', 1195, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AB' AND p.name = 'Aftonbladet Plus & Podme'), 'M', 'Month', 179, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AB' AND p.name = 'Aftonbladet Superpaketet'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'AB' AND p.name = 'Plus & SvenskHockey.tv'), 'M', 'Month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Basis'), 'W', 'Week', 54, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Basis'), 'M', 'Month', 229, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Basis'), 'Q', 'Quarter', 687, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Basis'), 'H', '6 months', 1374, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Basis'), 'Y', 'Year', 2748, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Familie'), 'M', 'Month', 349, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Familie'), 'Q', 'Quarter', 1047, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Familie'), 'H', '6 months', 2094, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Familie'), 'Y', 'Year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang'), 'W', 'Week', 87, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang'), 'M', 'Month', 379, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang'), 'Q', 'Quarter', 1137, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang'), 'H', '6 months', 2274, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang'), 'Y', 'Year', 4548, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Helg'), 'M', 'Month', 558, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Helg'), 'Q', 'Quarter', 1674, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Helg'), 'H', '6 months', 3348, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Helg'), 'Y', 'Year', 6696, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Komplett'), 'M', 'Month', 758, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Komplett'), 'Q', 'Quarter', 2274, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Komplett'), 'H', '6 months', 4548, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Full Tilgang Komplett'), 'Y', 'Year', 9096, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Helg'), 'W', 'Week', 113, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Helg'), 'M', 'Month', 489, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Helg'), 'Q', 'Quarter', 1467, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Helg'), 'H', '6 months', 2934, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Helg'), 'Y', 'Year', 5868, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Komplett'), 'M', 'Month', 689, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Komplett'), 'Q', 'Quarter', 2067, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Komplett'), 'H', '6 months', 4134, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Komplett'), 'Y', 'Year', 8268, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Premium'), 'W', 'Week', 66, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Premium'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Premium'), 'Q', 'Quarter', 897, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Premium'), 'H', '6 months', 1794, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'BT' AND p.name = 'Premium'), 'Y', 'Year', 3588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'Basis'), 'M', 'Month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'E24 og Dine Penger+'), 'M', 'Month', 269, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'E24 og Dine Penger+'), 'Y', 'Year', 2628, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'E24 uten deling'), 'M', 'Month', 198, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'Full Tilgang'), 'M', 'Month', 379, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'Full Tilgang'), 'Y', 'Year', 4548, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'Pro'), 'M', 'Month', 249, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'E24' AND p.name = 'Pro'), 'Y', 'Year', 1999, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni annonsfritt'), 'M', 'Month', 29, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Bundle'), 'M', 'Month', 249, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Bundle'), 'YM', 'Year/month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Bundle Bas'), 'M', 'Month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Bundle Bas'), 'YM', 'Year/month', 159, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Ekonomi'), 'M', 'Month', 189, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Ekonomi'), 'YM', 'Year/month', 159, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Ekonomi Bas'), 'M', 'Month', 179, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Ekonomi Bas'), 'YM', 'Year/month', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer'), 'M', 'Month', 139, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer'), 'Y', 'Year', 1188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer'), 'YM', 'Year/month', 99, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer Bas'), 'W', 'Week', 29, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer Bas'), 'M', 'Month', 119, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer Bas'), 'Y', 'Year', 948, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Mer Bas'), 'YM', 'Year/month', 79, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Superpaketet'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'OMNI' AND p.name = 'Omni Superpaketet'), 'YM', 'Year/month', 269, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'PM-NO' AND p.name = 'Podme NO'), 'M', 'Month', 79, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'R24' AND p.name = 'Randaberg24'), 'M', 'Month', 99, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'R24' AND p.name = 'Randaberg24'), 'Y', 'Year', 1188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Basis'), 'W', 'Week', 54, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Basis'), 'M', 'Month', 229, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Basis'), 'Q', 'Quarter', 687, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Basis'), 'H', '6 months', 1374, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Basis'), 'Y', 'Year', 2748, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Familie'), 'M', 'Month', 349, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Familie'), 'Q', 'Quarter', 1047, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Familie'), 'H', '6 months', 2094, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Familie'), 'Y', 'Year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang'), 'M', 'Month', 379, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang'), 'Q', 'Quarter', 1137, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang'), 'H', '6 months', 2274, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang'), 'Y', 'Year', 4548, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Helg'), 'M', 'Month', 568, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Helg'), 'Q', 'Quarter', 1704, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Helg'), 'H', '6 months', 3408, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Helg'), 'Y', 'Year', 6588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Komplett'), 'M', 'Month', 734, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Komplett'), 'Q', 'Quarter', 2202, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Komplett'), 'H', '6 months', 4404, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Full Tilgang Komplett'), 'Y', 'Year', 8448, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Helg'), 'W', 'Week', 115, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Helg'), 'M', 'Month', 499, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Helg'), 'Q', 'Quarter', 1497, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Helg'), 'H', '6 months', 2994, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Helg'), 'Y', 'Year', 5760, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Komplett'), 'M', 'Month', 665, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Komplett'), 'Q', 'Quarter', 1995, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Komplett'), 'H', '6 months', 3990, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Komplett'), 'Y', 'Year', 7620, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Premium'), 'W', 'Week', 66, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Premium'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Premium'), 'Q', 'Quarter', 897, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Premium'), 'H', '6 months', 1794, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SA' AND p.name = 'Premium'), 'Y', 'Year', 3588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'M', 'Month', 349, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'Q', 'Quarter', 1047, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'H', '6 months', 2094, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'Y', 'Year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'B2B_Y', 'B2B Year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_OS_M', 'Övriga Sverige Monthly', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_OS_Q', 'Övriga Sverige Quarterly', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_OS_H', 'Övriga Sverige Half-year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_OS_Y', 'Övriga Sverige Yearly', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_ST_M', 'Stockholm Monthly', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_ST_Q', 'Stockholm Quarterly', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_ST_H', 'Stockholm Half-year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'SE_ST_Y', 'Stockholm Yearly', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium'), 'FO_Y', 'Företag Year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital premium SP'), 'M', 'Month', 379, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital standard'), 'M', 'Month', 229, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital standard'), 'Q', 'Quarter', 687, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital standard'), 'H', '6 months', 1374, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital standard'), 'Y', 'Year', 2748, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital standard & Podme'), 'W', 'Week', 57, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD digital standard & Podme'), 'M', 'Month', 249, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_OS_M', 'Övriga Sverige Monthly', 799, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_OS_Q', 'Övriga Sverige Quarterly', 2397, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_OS_Y', 'Övriga Sverige Yearly', 9588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_ST_M', 'Stockholm Monthly', 799, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_ST_Q', 'Stockholm Quarterly', 2397, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_ST_H', 'Stockholm Half-year', 4794, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'SE_ST_Y', 'Stockholm Yearly', 9588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett alla dagar'), 'FO_Y', 'Företag Year', 10788, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett helg'), 'SE_ST_M', 'Stockholm Monthly', 519, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett helg'), 'SE_ST_Q', 'Stockholm Quarterly', 1557, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett helg'), 'SE_ST_H', 'Stockholm Half-year', 3114, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett helg'), 'SE_ST_Y', 'Stockholm Yearly', 5628, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett helg'), 'FO_Y', 'Företag Year', 7188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett sexdagars'), 'SE_OS_M', 'Övriga Sverige Monthly', 699, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett sexdagars'), 'SE_OS_Q', 'Övriga Sverige Quarterly', 2097, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett sexdagars'), 'SE_OS_H', 'Övriga Sverige Half-year', 4194, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett sexdagars'), 'SE_OS_Y', 'Övriga Sverige Yearly', 8388, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett tredagars'), 'SE_ST_M', 'Stockholm Monthly', 519, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett tredagars'), 'SE_ST_Q', 'Stockholm Quarterly', 1557, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett tredagars'), 'SE_ST_H', 'Stockholm Half-year', 3114, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett tredagars'), 'SE_ST_Y', 'Stockholm Yearly', 6228, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett vardag'), 'SE_ST_M', 'Stockholm Monthly', 499, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett vardag'), 'SE_ST_Q', 'Stockholm Quarterly', 1497, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett vardag'), 'SE_ST_H', 'Stockholm Half-year', 2994, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett vardag'), 'SE_ST_Y', 'Stockholm Yearly', 5988, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD komplett vardag'), 'FO_Y', 'Företag Year', 7188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD söndag'), 'SE_OS_M', 'Övriga Sverige Monthly', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD söndag'), 'SE_OS_Q', 'Övriga Sverige Quarterly', 447, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD söndag'), 'SE_OS_H', 'Övriga Sverige Half-year', 894, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD söndag'), 'SE_OS_Y', 'Övriga Sverige Yearly', 1788, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD söndag'), 'FO_Y', 'Företag Year', 1788, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD Superpaketet'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD Superpaketet - tillägg alla dagar'), 'M', 'Month', 69, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD Superpaketet - tillägg digital premium'), 'M', 'Month', 89, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD Superpaketet - tillägg helg'), 'M', 'Month', 69, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD taltidning'), 'Y', 'Year', 2304, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD taltidning - tillägg'), 'Y', 'Year', 480, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD Vinklubb'), 'M', 'Month', 39, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'SVD' AND p.name = 'SvD Vinklubb'), 'Y', 'Year', 399, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VEK' AND p.name = 'Vektklubb'), 'YM', 'Year/month', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VEK' AND p.name = 'Vektklubb'), 'HM', '6-month/month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VEK' AND p.name = 'Vektklubb'), 'QM', 'Quarter/month', 249, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VEK' AND p.name = 'Vektklubb'), 'APP_3M', 'In-app 3 months', 749, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'Dine Penger+'), 'W', 'Week', 39, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'Dine Penger+'), 'M', 'Month', 89, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'Dine Penger+'), 'Y', 'Year', 1059, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'MinMote strikk'), 'W', 'Week', 39, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis'), 'W', 'Week', 59, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis'), 'M', 'Month', 179, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis'), 'Q', 'Quarter', 499, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis'), 'H', '6 months', 949, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis'), 'Y', 'Year', 1788, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis med VG+'), 'M', 'Month', 209, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG eavis med VG+'), 'Y', 'Year', 2199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend fredag-lørdag'), 'M', 'Month', 329, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend fredag-lørdag'), 'Q', 'Quarter', 949, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend fredag-lørdag'), 'H', '6 months', 1849, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend fredag-lørdag'), 'Y', 'Year', 3599, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend fredag-lørdag'), 'PUB_1500', 'Pub 1500', 1875, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend fredag-lørdag'), 'PUB_2000', 'Pub 2000', 2500, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend hele helgen'), 'M', 'Month', 349, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend hele helgen'), 'Q', 'Quarter', 1047, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend hele helgen'), 'H', '6 months', 2094, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend hele helgen'), 'Y', 'Year', 4188, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend lørdag-søndag'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend lørdag-søndag'), 'Q', 'Quarter', 897, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend lørdag-søndag'), 'H', '6 months', 1794, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG Weekend lørdag-søndag'), 'Y', 'Year', 3588, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+'), 'W', 'Week', 39, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+'), 'M', 'Month', 99, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+'), 'Q', 'Quarter', 225, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+'), 'H', '6 months', 349, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+'), 'Y', 'Year', 799, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Basis'), 'W', 'Week', 59, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Basis'), 'M', 'Month', 99, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Basis'), 'Q', 'Quarter', 225, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Basis'), 'H', '6 months', 499, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Basis'), 'Y', 'Year', 799, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Flex'), 'M', 'Month', 299, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Full Tilgang'), 'M', 'Month', 379, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ og Dine Penger+'), 'W', 'Week', 59, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ og Dine Penger+'), 'M', 'Month', 119, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ og PodMe'), 'W', 'Week', 59, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ og PodMe'), 'M', 'Month', 119, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ og PodMe'), 'H', '6 months', 649, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ og PodMe'), 'Y', 'Year', 1199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Sport'), 'W', 'Week', 59, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Sport'), 'M', 'Month', 149, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'VG' AND p.name = 'VG+ Total'), 'M', 'Month', 179, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'W' AND p.name = 'Wellobe'), 'YM', 'Year/month', 199, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'W' AND p.name = 'Wellobe'), 'HM', '6-month/month', 229, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'W' AND p.name = 'Wellobe'), 'QM', 'Quarter/month', 279, 'standard');
INSERT INTO rate_plans (product_id, code, name, price, category) VALUES ((SELECT p.id FROM products p JOIN brands b ON p.brand_id = b.id WHERE b.code = 'W' AND p.name = 'Wellobe'), 'APP_6M', 'In-app 6 months', 1470, 'standard');
